site_name: David Magraner
site_url: https://davidmagraner.com

theme:
  name: material
  palette:
    # Dark professional scheme
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs        # Puts nav in top bar
    - navigation.tabs.sticky # Keeps tabs visible when scrolling
    - navigation.top         # Back to top button

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Contact: contact.md

extra_css:
  - stylesheets/extra.css