site_name: David Magraner Villalba
site_url: https://davidmagraner.com

theme:
  name: material
  custom_dir: overrides
  logo: /img/blue_logo.png
  palette:
    # Dark professional scheme
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs.sticky # Keeps tabs visible when scrolling
    - navigation.top         # Back to top button
  icon:
    repo: fontawesome/fontawesome

plugins: [] # Since searchbox is not included, there will be no searchbox.

markdown_extensions:
  - attr_list  # This is usually the key fix
  - md_in_html # This is often required if you mix Markdown and HTML like this
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - About Me: index.md
  - My Data Career: career.md
  - Projects: 
    - From OLTP to OLAP: project1.md
    - Route Calculator: project2.md
    - Fiscal Multipliers: project3.md
    - Invoice Database: project4.md
  - Contact & Links: contact.md

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/davidmagraner/ 
    - icon: fontawesome/brands/github 
      link: https://github.com/mavidvd

extra_css:
  - stylesheets/extra.css
  - stylesheets/cv.css