site_name: David Magraner Villalba
site_url: https://davidmagraner.com

theme:
  name: material
  logo: /img/blue_logo.png
  icon:
    logo: '' # Set logo icon to an empty string
  palette:
    # Dark professional scheme
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs.sticky # Keeps tabs visible when scrolling
    - navigation.top         # Back to top button

plugins: [] # Since searchbox is not included, there will be no searchbox.

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Contact: contact.md

extra_css:
  - stylesheets/extra.css