site_name: David Magraner Villalba
site_url: https://davidmagraner.com

theme:
  name: material
  custom_dir: overrides
  logo: /img/blue_logo.png
  palette:
    # Dark professional scheme
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs.sticky # Keeps tabs visible when scrolling
    - navigation.top         # Back to top button

plugins: [] # Since searchbox is not included, there will be no searchbox.

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Contact & Scheduling: contact.md

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/davidmagraner/ 
    - icon: fontawesome/brands/github 
      link: https://github.com/mavidvd

extra_css:
  - stylesheets/extra.css